packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  canvas: true
  cbor-extract: true
  esbuild: false
  msgpackr-extract: true
  protobufjs: true
  tree-sitter: true
  unrs-resolver: true
